import { CatalogItem } from "catalog-core";

export const items = [
    new CatalogItem({ id: 1, name: "Sourdough Loaf", price: 7, category: "bakery", imageUrl: "/sourdough.png" }),
    new CatalogItem({ id: 2, name: "Croissant", price: 4, category: "bakery", imageUrl: "/croissant.png" }),
    new CatalogItem({ id: 3, name: "Bagel", price: 3, category: "bakery", imageUrl: "/bagel.png" }),
    new CatalogItem({ id: 4, name: "Baguette", price: 5, category: "bakery", imageUrl: "/baguette.png" }),
    new CatalogItem({ id: 5, name: "Avocado", price: 2, category: "produce", imageUrl: "/avocado.png" }),
    new CatalogItem({ id: 6, name: "Heirloom Tomato", price: 4, category: "produce", imageUrl: "/tomato.png" }),
    new CatalogItem({ id: 7, name: "Strawberries", price: 6, category: "produce", imageUrl: "/strawberries.png" }),
    new CatalogItem({ id: 8, name: "Blueberries", price: 5, category: "produce", imageUrl: "/blueberries.png" }),
    new CatalogItem({ id: 9, name: "Spinach", price: 3, category: "produce", imageUrl: "/spinach.png" }),
    new CatalogItem({ id: 10, name: "Sweet Corn", price: 2, category: "produce", imageUrl: "/corn.png" }),
    new CatalogItem({ id: 11, name: "Cheddar", price: 8, category: "dairy", imageUrl: "/cheddar.png" }),
    new CatalogItem({ id: 12, name: "Mozzarella", price: 7, category: "dairy", imageUrl: "/mozzarella.png" }),
    new CatalogItem({ id: 13, name: "Greek Yogurt", price: 5, category: "dairy", imageUrl: "/yogurt.png" }),
    new CatalogItem({ id: 14, name: "Butter", price: 6, category: "dairy", imageUrl: "/butter.png" }),
    new CatalogItem({ id: 15, name: "Eggs", price: 4, category: "dairy", imageUrl: "/eggs.png" }),
    new CatalogItem({ id: 16, name: "Salmon Fillet", price: 18, category: "seafood", imageUrl: "/salmon.png" }),
    new CatalogItem({ id: 17, name: "Shrimp", price: 14, category: "seafood", imageUrl: "/shrimp.png" }),
    new CatalogItem({ id: 18, name: "Tuna Steak", price: 16, category: "seafood", imageUrl: "/tuna.png" }),
    new CatalogItem({ id: 19, name: "Chicken Breast", price: 12, category: "meat", imageUrl: "/chicken.png" }),
    new CatalogItem({ id: 20, name: "Ribeye Steak", price: 28, category: "meat", imageUrl: "/ribeye.png" }),
    new CatalogItem({ id: 21, name: "Bacon", price: 9, category: "meat", imageUrl: "/bacon.png" }),
    new CatalogItem({ id: 22, name: "Italian Sausage", price: 10, category: "meat", imageUrl: "/sausage.png" }),
    new CatalogItem({ id: 23, name: "Spaghetti", price: 3, category: "pantry", imageUrl: "/spaghetti.png" }),
    new CatalogItem({ id: 24, name: "Olive Oil", price: 11, category: "pantry", imageUrl: "/olive-oil.png" }),
    new CatalogItem({ id: 25, name: "Basmati Rice", price: 6, category: "pantry", imageUrl: "/rice.png" }),
    new CatalogItem({ id: 26, name: "Black Beans", price: 2, category: "pantry", imageUrl: "/black-beans.png" }),
    new CatalogItem({ id: 27, name: "Tomato Sauce", price: 4, category: "pantry", imageUrl: "/tomato-sauce.png" }),
    new CatalogItem({ id: 28, name: "Honey", price: 8, category: "pantry", imageUrl: "/honey.png" }),
    new CatalogItem({ id: 29, name: "Dark Chocolate", price: 5, category: "snacks", imageUrl: "/chocolate.png" }),
    new CatalogItem({ id: 30, name: "Potato Chips", price: 3, category: "snacks", imageUrl: "/chips.png" }),
    new CatalogItem({ id: 31, name: "Trail Mix", price: 7, category: "snacks", imageUrl: "/trail-mix.png" }),
    new CatalogItem({ id: 32, name: "Granola Bar", price: 2, category: "snacks", imageUrl: "/granola-bar.png" }),
    new CatalogItem({ id: 33, name: "Espresso Beans", price: 13, category: "beverages", imageUrl: "/espresso.png" }),
    new CatalogItem({ id: 34, name: "Green Tea", price: 6, category: "beverages", imageUrl: "/green-tea.png" }),
    new CatalogItem({ id: 35, name: "Orange Juice", price: 5, category: "beverages", imageUrl: "/orange-juice.png" }),
    new CatalogItem({ id: 36, name: "Sparkling Water", price: 2, category: "beverages", imageUrl: "/sparkling-water.png" }),
    new CatalogItem({ id: 37, name: "Vanilla Ice Cream", price: 7, category: "frozen", imageUrl: "/ice-cream.png" }),
    new CatalogItem({ id: 38, name: "Frozen Peas", price: 3, category: "frozen", imageUrl: "/peas.png" }),
    new CatalogItem({ id: 39, name: "Pizza Margherita", price: 12, category: "frozen", imageUrl: "/pizza.png" }),
    new CatalogItem({ id: 40, name: "Miso Soup Mix", price: 4, category: "pantry", imageUrl: "/miso.png" })
]
